//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace ChargeWin.WebStandardInfo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="StandardInfoSoap", Namespace="http://tempuri.org/")]
    public partial class StandardInfo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public StandardInfo() {
            this.Url = global::ChargeWin.Properties.Settings.Default.ParkFeeMag_WebStandardInfo_StandardInfo;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddCompletedEventHandler AddCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Add", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Add(FeeStandard feeModel) {
            object[] results = this.Invoke("Add", new object[] {
                        feeModel});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddAsync(FeeStandard feeModel) {
            this.AddAsync(feeModel, null);
        }
        
        /// <remarks/>
        public void AddAsync(FeeStandard feeModel, object userState) {
            if ((this.AddOperationCompleted == null)) {
                this.AddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOperationCompleted);
            }
            this.InvokeAsync("Add", new object[] {
                        feeModel}, this.AddOperationCompleted, userState);
        }
        
        private void OnAddOperationCompleted(object arg) {
            if ((this.AddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCompleted(this, new AddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FeeStandard {
        
        private int idField;
        
        private System.Nullable<int> feeStandardIdField;
        
        private System.Nullable<decimal> feetopField;
        
        private System.Nullable<int> freeMinutesField;
        
        private string feeTypeField;
        
        private string standardFeeField;
        
        private System.Nullable<decimal> feePerViewField;
        
        private System.Nullable<int> dayStartHourField;
        
        private System.Nullable<int> dayStartMinuteField;
        
        private System.Nullable<int> dayFirstTimeHourField;
        
        private System.Nullable<int> dayFirstTimeMinuteField;
        
        private System.Nullable<int> dayTimeUnitField;
        
        private System.Nullable<decimal> dayUnitFeeField;
        
        private System.Nullable<decimal> dayTopFeeField;
        
        private System.Nullable<decimal> dayLowestFeeField;
        
        private System.Nullable<int> nightStartHourField;
        
        private System.Nullable<int> nightStartMinuteField;
        
        private System.Nullable<int> nightFirstTimeHourField;
        
        private System.Nullable<int> nightFirstTimeMinuteField;
        
        private System.Nullable<int> nightTimeUnitField;
        
        private System.Nullable<decimal> nightUnitFeeField;
        
        private System.Nullable<decimal> nightTopFeeField;
        
        private System.Nullable<decimal> nightLowestFeeField;
        
        private System.Nullable<int> sTTimeUnieField;
        
        private System.Nullable<decimal> sTUnieFeeField;
        
        private System.Nullable<int> sTFirstTimeUnitHourField;
        
        private System.Nullable<int> sTFirstTimeUnitMinuteField;
        
        private System.Nullable<decimal> sTFirstTimeFeeField;
        
        private System.Nullable<decimal> sTOverNightFeeField;
        
        private string operatorNameField;
        
        private System.Nullable<System.DateTime> operateTimeField;
        
        private string companyCodeField;
        
        private string parkIdField;
        
        private string carTypeField;
        
        private bool isUploadField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> FeeStandardId {
            get {
                return this.feeStandardIdField;
            }
            set {
                this.feeStandardIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Feetop {
            get {
                return this.feetopField;
            }
            set {
                this.feetopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> FreeMinutes {
            get {
                return this.freeMinutesField;
            }
            set {
                this.freeMinutesField = value;
            }
        }
        
        /// <remarks/>
        public string FeeType {
            get {
                return this.feeTypeField;
            }
            set {
                this.feeTypeField = value;
            }
        }
        
        /// <remarks/>
        public string StandardFee {
            get {
                return this.standardFeeField;
            }
            set {
                this.standardFeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> FeePerView {
            get {
                return this.feePerViewField;
            }
            set {
                this.feePerViewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DayStartHour {
            get {
                return this.dayStartHourField;
            }
            set {
                this.dayStartHourField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DayStartMinute {
            get {
                return this.dayStartMinuteField;
            }
            set {
                this.dayStartMinuteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DayFirstTimeHour {
            get {
                return this.dayFirstTimeHourField;
            }
            set {
                this.dayFirstTimeHourField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DayFirstTimeMinute {
            get {
                return this.dayFirstTimeMinuteField;
            }
            set {
                this.dayFirstTimeMinuteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DayTimeUnit {
            get {
                return this.dayTimeUnitField;
            }
            set {
                this.dayTimeUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> DayUnitFee {
            get {
                return this.dayUnitFeeField;
            }
            set {
                this.dayUnitFeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> DayTopFee {
            get {
                return this.dayTopFeeField;
            }
            set {
                this.dayTopFeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> DayLowestFee {
            get {
                return this.dayLowestFeeField;
            }
            set {
                this.dayLowestFeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NightStartHour {
            get {
                return this.nightStartHourField;
            }
            set {
                this.nightStartHourField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NightStartMinute {
            get {
                return this.nightStartMinuteField;
            }
            set {
                this.nightStartMinuteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NightFirstTimeHour {
            get {
                return this.nightFirstTimeHourField;
            }
            set {
                this.nightFirstTimeHourField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NightFirstTimeMinute {
            get {
                return this.nightFirstTimeMinuteField;
            }
            set {
                this.nightFirstTimeMinuteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NightTimeUnit {
            get {
                return this.nightTimeUnitField;
            }
            set {
                this.nightTimeUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> NightUnitFee {
            get {
                return this.nightUnitFeeField;
            }
            set {
                this.nightUnitFeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> NightTopFee {
            get {
                return this.nightTopFeeField;
            }
            set {
                this.nightTopFeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> NightLowestFee {
            get {
                return this.nightLowestFeeField;
            }
            set {
                this.nightLowestFeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> STTimeUnie {
            get {
                return this.sTTimeUnieField;
            }
            set {
                this.sTTimeUnieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> STUnieFee {
            get {
                return this.sTUnieFeeField;
            }
            set {
                this.sTUnieFeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> STFirstTimeUnitHour {
            get {
                return this.sTFirstTimeUnitHourField;
            }
            set {
                this.sTFirstTimeUnitHourField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> STFirstTimeUnitMinute {
            get {
                return this.sTFirstTimeUnitMinuteField;
            }
            set {
                this.sTFirstTimeUnitMinuteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> STFirstTimeFee {
            get {
                return this.sTFirstTimeFeeField;
            }
            set {
                this.sTFirstTimeFeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> STOverNightFee {
            get {
                return this.sTOverNightFeeField;
            }
            set {
                this.sTOverNightFeeField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorName {
            get {
                return this.operatorNameField;
            }
            set {
                this.operatorNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> OperateTime {
            get {
                return this.operateTimeField;
            }
            set {
                this.operateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ParkId {
            get {
                return this.parkIdField;
            }
            set {
                this.parkIdField = value;
            }
        }
        
        /// <remarks/>
        public string CarType {
            get {
                return this.carTypeField;
            }
            set {
                this.carTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsUpload {
            get {
                return this.isUploadField;
            }
            set {
                this.isUploadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AddCompletedEventHandler(object sender, AddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591