//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChargeWin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://zst.gzwulian.com/ClientService/WebServices/StandardInfo.asmx")]
        public string ParkFeeMag_WebStandardInfo_StandardInfo {
            get {
                return ((string)(this["ParkFeeMag_WebStandardInfo_StandardInfo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://zst.gzwulian.com/ClientService/WebServices/ChargeInfo.asmx")]
        public string ParkFeeMag_WebChargeInfo_ChargeInfo {
            get {
                return ((string)(this["ParkFeeMag_WebChargeInfo_ChargeInfo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://zst.gzwulian.com/ClientService/WebServices/CarTypeInfo.asmx")]
        public string ParkFeeMag_WebCarTypeInfo_CarTypeInfo {
            get {
                return ((string)(this["ParkFeeMag_WebCarTypeInfo_CarTypeInfo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://zst.gzwulian.com/ClientService/WebServices/WorkInfo.asmx")]
        public string ParkFeeMag_WebWorkInfo_WorkInfo {
            get {
                return ((string)(this["ParkFeeMag_WebWorkInfo_WorkInfo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://zst.gzwulian.com/ClientService/WebServices/OperatorInfo.asmx")]
        public string ParkFeeMag_WebOperatorInfo_OperatorInfo {
            get {
                return ((string)(this["ParkFeeMag_WebOperatorInfo_OperatorInfo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://zst.gzwulian.com/ClientService/WebServices/FInOut.asmx")]
        public string ParkFeeMag_WebFInOutInfo_FInOutInfo {
            get {
                return ((string)(this["ParkFeeMag_WebFInOutInfo_FInOutInfo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://zst.gzwulian.com/ClientService/WebServices/FCustomerInfo.asmx")]
        public string ParkFeeMag_WebFCustomerInfo_FCustomerInfo {
            get {
                return ((string)(this["ParkFeeMag_WebFCustomerInfo_FCustomerInfo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://zst.gzwulian.com/ClientService/WebServices/ClearInfo.asmx")]
        public string ParkFeeMag_WebClearInfo_ClearInfo {
            get {
                return ((string)(this["ParkFeeMag_WebClearInfo_ClearInfo"]));
            }
        }
    }
}
