//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace ChargeWin.WebFCustomerInfo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FCustomerInfoSoap", Namespace="http://tempuri.org/")]
    public partial class FCustomerInfo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FCustomerInfo() {
            this.Url = global::ChargeWin.Properties.Settings.Default.ParkFeeMag_WebFCustomerInfo_FCustomerInfo;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddCompletedEventHandler AddCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Add", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Add(FCustomer fcustomer) {
            object[] results = this.Invoke("Add", new object[] {
                        fcustomer});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddAsync(FCustomer fcustomer) {
            this.AddAsync(fcustomer, null);
        }
        
        /// <remarks/>
        public void AddAsync(FCustomer fcustomer, object userState) {
            if ((this.AddOperationCompleted == null)) {
                this.AddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOperationCompleted);
            }
            this.InvokeAsync("Add", new object[] {
                        fcustomer}, this.AddOperationCompleted, userState);
        }
        
        private void OnAddOperationCompleted(object arg) {
            if ((this.AddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCompleted(this, new AddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FCustomer {
        
        private int idField;
        
        private string nameField;
        
        private string plateIdField;
        
        private bool enableField;
        
        private System.Nullable<System.DateTime> createTimeField;
        
        private System.Nullable<System.DateTime> overTimeField;
        
        private bool startTimeSegField;
        
        private string timeSegField;
        
        private bool needAlarmField;
        
        private string codeField;
        
        private string imgPathField;
        
        private string plateColorField;
        
        private string genderField;
        
        private string addressField;
        
        private string departmentField;
        
        private string positionField;
        
        private string joinDateField;
        
        private string birthDateField;
        
        private string idCardField;
        
        private bool isMarriedField;
        
        private string topDegreeField;
        
        private string affiliationField;
        
        private string pathField;
        
        private string schoolField;
        
        private string majouField;
        
        private string telphoneField;
        
        private string postalCodeField;
        
        private string nativePlaceField;
        
        private string parkIdField;
        
        private string operatorNameField;
        
        private System.Nullable<System.DateTime> addTimeField;
        
        private string companyCodeField;
        
        private string carTypeField;
        
        private bool isUploadField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string PlateId {
            get {
                return this.plateIdField;
            }
            set {
                this.plateIdField = value;
            }
        }
        
        /// <remarks/>
        public bool Enable {
            get {
                return this.enableField;
            }
            set {
                this.enableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> OverTime {
            get {
                return this.overTimeField;
            }
            set {
                this.overTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool StartTimeSeg {
            get {
                return this.startTimeSegField;
            }
            set {
                this.startTimeSegField = value;
            }
        }
        
        /// <remarks/>
        public string TimeSeg {
            get {
                return this.timeSegField;
            }
            set {
                this.timeSegField = value;
            }
        }
        
        /// <remarks/>
        public bool NeedAlarm {
            get {
                return this.needAlarmField;
            }
            set {
                this.needAlarmField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string ImgPath {
            get {
                return this.imgPathField;
            }
            set {
                this.imgPathField = value;
            }
        }
        
        /// <remarks/>
        public string PlateColor {
            get {
                return this.plateColorField;
            }
            set {
                this.plateColorField = value;
            }
        }
        
        /// <remarks/>
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public string Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public string JoinDate {
            get {
                return this.joinDateField;
            }
            set {
                this.joinDateField = value;
            }
        }
        
        /// <remarks/>
        public string BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        public string IdCard {
            get {
                return this.idCardField;
            }
            set {
                this.idCardField = value;
            }
        }
        
        /// <remarks/>
        public bool IsMarried {
            get {
                return this.isMarriedField;
            }
            set {
                this.isMarriedField = value;
            }
        }
        
        /// <remarks/>
        public string TopDegree {
            get {
                return this.topDegreeField;
            }
            set {
                this.topDegreeField = value;
            }
        }
        
        /// <remarks/>
        public string Affiliation {
            get {
                return this.affiliationField;
            }
            set {
                this.affiliationField = value;
            }
        }
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public string School {
            get {
                return this.schoolField;
            }
            set {
                this.schoolField = value;
            }
        }
        
        /// <remarks/>
        public string Majou {
            get {
                return this.majouField;
            }
            set {
                this.majouField = value;
            }
        }
        
        /// <remarks/>
        public string Telphone {
            get {
                return this.telphoneField;
            }
            set {
                this.telphoneField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string NativePlace {
            get {
                return this.nativePlaceField;
            }
            set {
                this.nativePlaceField = value;
            }
        }
        
        /// <remarks/>
        public string ParkId {
            get {
                return this.parkIdField;
            }
            set {
                this.parkIdField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorName {
            get {
                return this.operatorNameField;
            }
            set {
                this.operatorNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> AddTime {
            get {
                return this.addTimeField;
            }
            set {
                this.addTimeField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CarType {
            get {
                return this.carTypeField;
            }
            set {
                this.carTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsUpload {
            get {
                return this.isUploadField;
            }
            set {
                this.isUploadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AddCompletedEventHandler(object sender, AddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591